import json
import os

from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

api_key = os.getenv("LITELLM_API_KEY")

client = OpenAI(
    base_url="https://www.litellm.org/",
    api_key=api_key,
)

# 1. Define a list of callable tools for the model
tools = [
    {
        "type": "function",
        "name": "get_stock_price",
        "description": "Retrieve the current stock price for a given ticker symbol (in USD).",
        "parameters": {
            "type": "object",
            "properties": {
                "ticker": {
                    "type": "string",
                    "description": "The stock ticker symbol, e.g., AAPL, MSFT.",
                },
            },
            "required": ["ticker"],
        },
    },
]


def get_stock_price(ticker: str) -> float:
    """
    Mock function to simulate fetching a stock price.
    In production, replace this with a real API call (e.g., Yahoo Finance, Alpha Vantage).
    """
    mock_prices = {"AAPL": 175.50, "MSFT": 332.80}
    return mock_prices.get(ticker.upper(), 0.0)


# Create a running input list we will add to over time
input_list = [
    {
        "role": "user",
        "content": "Compare Apple and Microsoft's stock prices today. Which one performed better?",
    }
]

# 2. Prompt the model with tools defined
response = client.responses.create(
    model="azure/gpt-5-mini",
    tools=tools,
    input=input_list,
)

# Save function call outputs for subsequent requests
input_list += response.output

for item in response.output:
    if item.type == "function_call":
        if item.name == "get_stock_price":
            # 3. Execute the function logic for get_stock_price
            ticker = json.loads(item.arguments)["ticker"]
            result = get_stock_price(ticker)

            # 4. Provide function call results to the model
            input_list.append(
                {
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": str(result),
                }
            )

print("Final input:")
print(input_list)

response = client.responses.create(
    model="azure/gpt-5-mini",
    instructions="Respond only with a price generated by a tool.",
    tools=tools,
    input=input_list,
)

# 5. The model should be able to give a response!
print("Final output:")
print(response.model_dump_json(indent=2))
print("\n" + response.output_text)
